'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property AddressID As Integer
    Public Property StreetAddress1 As String
    Public Property StreetAddress2 As String
    Public Property City As String
    Public Property State As String
    Public Property ZipCode As String
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateCreated As Date
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property Archived As Boolean

    Public Overridable Property Authors As ICollection(Of Author) = New HashSet(Of Author)
    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)

End Class
