'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Book
    Public Property BookID As Integer
    Public Property ISBN As String
    Public Property Title As String
    Public Property Description As String
    Public Property Author As Nullable(Of Integer)
    Public Property QuantityOnHand As Nullable(Of Integer)
    Public Property Cost As Nullable(Of Decimal)
    Public Property Price As Nullable(Of Decimal)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateCreated As Date
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property Archived As Boolean

    Public Overridable Property Author1 As Author
    Public Overridable Property OrderLines As ICollection(Of OrderLine) = New HashSet(Of OrderLine)
    Public Overridable Property Categories As ICollection(Of Category) = New HashSet(Of Category)

End Class
