'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property CustomerID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Address As Nullable(Of Integer)
    Public Property PhoneNumber As String
    Public Property Fax As String
    Public Property Mobile As String
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateCreated As Date
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property Archived As Boolean

    Public Overridable Property Address1 As Address
    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
