'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class File
    Public Property FileID As Integer
    Public Property FileName As String
    Public Property FriendlyName As String
    Public Property FileDescription As String
    Public Property DateCreated As Date

End Class
