'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderLine
    Public Property OrderLineID As Integer
    Public Property Order As Integer
    Public Property Book As Integer
    Public Property Quantity As Nullable(Of Integer)
    Public Property Price As Nullable(Of Decimal)

    Public Overridable Property Book1 As Book
    Public Overridable Property Order1 As Order

End Class
