'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Boot_Camp_Website

    Partial Public Class Books

        '''<summary>
        '''RadWindowManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

        '''<summary>
        '''RadWindow1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

        '''<summary>
        '''ddlAllBooks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAllBooks As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnAddBook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddBook As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
