'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LinqDemo

    '''<summary>
    '''ddlQuerySelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuerySelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblParam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParam1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtParam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParam1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlParamList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParamList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblParam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParam2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtParam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParam2 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddlParamList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParamList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblParam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParam3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtParam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParam3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRunQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunQuery As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rgResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgResults As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rfvParam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvParam1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvParam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvParam2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''vsSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsSummary As Global.System.Web.UI.WebControls.ValidationSummary
End Class
